version: '3.7'
services:
  api:
    build: 
      context: .
      dockerfile: api.Dockerfile
    ports: 
      - '3333:3333'
    environment: 
      VK_APP_SECRET: SOME_APP_SECRET
      VK_APP_DOMAIN: http://localhost:4200/
      VK_GRAPHQL_SCHEMA_PATH: apps/api/schema.graphql
      VK_DATABASE: postgresql://postgres:postgres@postgres:5432/prisma
    depends_on:
      - postgres
  ui:
    build:
      context: .
      dockerfile: ui.Dockerfile
    ports: 
      - '4200:8080'
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  migration:
    build:
      context: ./libs/api-interface/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      VK_DATABASE: postgresql://postgres:postgres@postgres:5432/prisma
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
volumes:
  postgres:
