service: visual-knight-platform

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  profile: ${env:AWS_PROFILE_VISUAL_KNIGHT_PLATFORM}
  apiGateway:
    minimumCompressionSize: 1024
  tracing:
    apiGateway: true
    lambda: true
  environment:
    region: ${opt:region, 'eu-central-1'}

plugins:
  - serverless-offline

package:
  individually: true

functions:
  webapp:
    handler: apps/backend-webapp/dist/index.handler
    package:
      artifact: apps/backend-webapp/dist/webapp.zip

    events:
      - http:
          method: any
          path: /webapp

  comparison:
    handler: apps/backend-comparison/dist/index.handler
    package:
      artifact: apps/backend-comparison/dist/comparison.zip

    events:
      - http:
          cors: true
          method: any
          path: /comparison
      - http:
          cors: true
          path: '/comparison/{proxy+}'
          method: any

  processTestsessionImage:
    handler: apps/lambdas/dist/processTestsessionImage.handler
    package:
      artifact: apps/lambdas/dist/processTestsessionImage.zip
    environment:
      # needs permission to call CREATE_DIFF_FUNCTION_NAME
      # get function reference name for CREATE_DIFF_FUNCTION_NAME
      CREATE_DIFF_FUNCTION_NAME: ${self:provider.stage}-createDiff
      # PRISMA: ${ssm:/${self:provider.stage}/visual-knigth-platform/prisma~true}
      PRISMA: some-endpoint
    events:
      - s3:
          bucket: visual-knight-platform-photos
          event: s3:ObjectCreated:*
          rules:
            - suffix: .screenshot.png

  createDiff:
    handler: apps/lambdas/dist/createDiff.handler
    package:
      artifact: apps/lambdas/dist/createDiff.zip
    environment:
      # PRISMA: ${ssm:/${self:provider.stage}/visual-knigth-platform/prisma~true}
      PRISMA: some-endpoint
      threshold: 12
      includeAA: true
