name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
      env: 
        VK_DATABASE: file:../../tmp/visual-knight.db
    - name: Run API tests
      run: npx ng test api
    - name: Run UI tests
      run: npx ng test visual-knight
